name: invisio.ca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.857827594038099
title: InVisio Wealth Advisory Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070908'
    - '#336a88'
    - '#3f3f3f'
    - '#85a6b9'
  brandStrength: 0.5606787882279605
  lightness: 0.09708788641728461
  saturation: 0.4420449435710907
  rhythmicContrast: 0.861151936929673
purpose: []
