name: invisio.ca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76356
title: InVisio Wealth Advisory Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070908'
    - '#336a88'
    - '#3f3f3f'
    - '#85a6b9'
  brandStrength: 0
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
