name: invisio.ca
favicon: null
layout_spectrum: 0.33172173728235066
typography_spectrum: 0.857827594038099
title: InVisio Wealth Advisory Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5606787882279605
  lightness: 0.09708788641728461
  saturation: 0.4420449435710907
  rhythmicContrast: 0.861151936929673
purpose: []
